ledger/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from . import form

app_name = 'ledger'

urlpatterns = [
    # 应用主页
    path('', views.index, name="index"),
    # 展示所有账单信息
    path('all_bills/', views.all_bills, name="all_bills"),
    # 记一笔页面
    path('record/', views.record, name="record"),
    # 帮助页面
    path('FAQ/', views.help, name="help"),
    # 提交表单数据
    path('form_submit/', form.form_submit, name="form_submit"),
]

pocket_book/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ledger.urls', namespace='ledger')),
    path('', include('users.urls', namespace='users')),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'
LoginView.template_name = 'users/login.html'
urlpatterns = [
    # 登录页面
    path('users/login/', LoginView.as_view(), name='login'),
    # 注销
    path('logout/', views.logout_view, name='logout'),
    # 注册
    path('register/', views.register, name='register'),
]

ledger/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

ledger/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse


@login_required
# 网站主页
def index(request):
    return render(request, "ledger/index.html")


@login_required
# 展示所有账单信息
def all_bills(request):
    return render(request, "ledger/all_bills.html")


@login_required
# 记一笔页面
def record(request):
    return render(request, "ledger/record.html")


# 网站帮助
def help(request):
    return render(request, "ledger/help.html")

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, authenticate  # 导入django自带的登陆验证模块
from django.contrib.auth.forms import UserCreationForm
from . import models


def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('ledger:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重新定向到主页
            authenticated_user = authenticate(username=new_user.name, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('ledger:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)


def login(request):
    if request.method == "POST":
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        message = "所有字段都必须填写！"
        if username and password:  # 确保用户名和密码都不为空
            username = username.strip()
            try:
                user = models.users.objects.get(name=username)
                if user.password == password:
                    return HttpResponseRedirect('/index/')
                else:
                    message = "密码不正确！"
            except:
                message = "用户名不存在！"
        return render(request, 'users/login.html', {"message": message})
    return render(request, 'users/login.html')

ledger/templates/ledger/all_bills.html
{% extends "ledger/base.html" %}
{% block header %}
    <!DOCTYPE html>
    <html lang="zh">
    <head>
        <meta charset="UTF-8">
        <title>所有账单</title>
    </head>
{% endblock header %}
{% block content %}
    <body>
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                data-bs-toggle="dropdown" aria-expanded="false">
            切换账本
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="#">默认账本</a></li>
            <li><a class="dropdown-item" href="#">新建账本</a></li>
        </ul>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">类型</th>
            <th scope="col">时间</th>
            <th scope="col">分类</th>
            <th scope="col">金额</th>
        </tr>
        </thead>
    </table>
    <div>
        <span class="border border-5">总支出：</span><br><br>
        <span class="border border-5">总收入：</span>
    </div>
    </body>
{% endblock content %}
</html>

ledger/templates/ledger/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>涂涂记账</title>
    <!--引入bootstrap-->
    <link rel="stylesheet" href="../../static/bootstrap/bootstrap-5.0.0/css/bootstrap.css">
    <script src="../../static/bootstrap/jQuery/jquery-3.6.0.js"></script>
    <script src="../../static/bootstrap/bootstrap-5.0.0/js/bootstrap.bundle.js"></script>
    <script src="../../static/laydate/laydate.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <style>
        .a_btn {
            text-decoration: none;
            color: #333;
            font-weight: bolder;
        }

        .cell {
            height: 40px;
            display: table-cell;
            vertical-align: middle;
        }

        .pop {
            width: 0;
            position: fixed;
            top: 60px;
            right: 0;
            background: #0d6efd;
            word-break: break-all;
            transition: width 0.5s cubic-bezier(0.68, -0.55, 0.27, 1.55) 0s;
        }

        .Play_such {
            border: solid #0d6efd; /*边框颜色*/
            background: #ffffff; /* 背景颜色 */
            z-index: 9988;
            border-radius: 10px;
        }
    </style>
    <!--侧边弹出栏-->
    <script type="text/javascript">
        function narrow() {
            var isTrue = parseInt($('#clickSide').attr('value'));

            if (isTrue == 0) {
                $('.pop').css({'width': '200px'}); //弹出的宽度
                $('#clickSide').attr('value', 1);
            } else {
                $('.pop').css({'width': '0'}); //收起时显示的宽度
                $('#clickSide').attr('value', 0);
            }
            return false;
        }
    </script>
    <!--防止页面后退-->
    <script>
        $(function () {
            history.pushState(null, null, document.URL);
            window.addEventListener('popstate', function () {
                history.pushState(null, null, document.URL);
            });
        })
    </script>

    <script type="text/javascript">
        $(function () {
            $(".dropdown-item").mouseover(function () {
                $(this).children("select").show();
            })
            $(".dropdown-item").mouseout(function () {
                $(this).children("select").hide();
            })
        })
    </script>

    <script type="text/javascript">
        function showsubMenu(li) {
            var submenu = li.getElementsByTagName("ul")[0];
            submenu.style.display = "block";
        }

        function hidesubMenu(li) {
            var submenu = li.getElementsByTagName("ul")[0];
            submenu.style.display = "none";
        }
    </script>
    <!-- 日历部分-->
    <script src="../../static/laydate/laydate.js"></script>
    <script>
        laydate.render({
            elem: '#test-range'
            , range: ['#startDate', '#endDate']
        });
    </script>

    <script>
        var get_start_month;
        var get_start_day;

        //获取input框中的value值
        function getInputVal() {
            const StartInputBox = document.querySelectorAll('.start-input-a')[0];
            const EndInputBox = document.querySelectorAll('.end-input-a')[0];
            //以‘-’分割开始日期
            var strstart = StartInputBox.value.split("-");
            for (let i = 0; i < strstart.length; i++) {
                var get_start_year = strstart[0];
                get_start_month = strstart[1];
                get_start_day = strstart[2];
            }
            fifter_month(get_start_month);
            fifter_day(get_start_day);

            //以‘-’分割结束日期
            var strend = EndInputBox.value.split("-");
            for (let i = 0; i < strend.length; i++) {
                var get_end_year = strend[0];
                var get_end_month = strend[1];
                var get_end_day = strend[2];
            }
        }
    </script>

</head>

<body>
<! -- 静态导航栏 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand">涂涂记账</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <button type="button" class="btn btn-primary"
                            onclick="window.location.href = '{% url "ledger:index" %}'">主页
                    </button>
                </li>&nbsp;

                <li class="nav-item">
                    <button type="button" class="btn btn-primary"
                            onclick="window.location.href = '{% url "ledger:help" %}'">帮助
                    </button>
                </li>&nbsp;

                <div class="layui-form-item">
                    <div class="layui-inline">
                        <div class="layui-inline cell" id="test-range">
                            <span class="layui-input-inline">
                                <input type="text" id="startDate" class="layui-input start-input-a" placeholder="开始日期">
                                <span class="layui-form-mid">-></span>
                                <input type="text" id="endDate" class="layui-input end-input-a" placeholder="结束日期">
                            </span>
                        </div>
                    </div>
                </div>&nbsp;

                <li class="nav-item">
                    <button type="button" class="btn btn-primary" onclick="getInputVal()">查询
                    </button>
                </li>
            </ul>
        {% endif %}
        {% if user.is_authenticated %}
            <form class="d-flex">
            <button id="clickSide" onclick="narrow()" type="button" class="btn btn-primary">{{ user.username }}</button>
            <div class="pop">
                <!--    弹出的内容-->
                <div class="Play_such">用户名:</div>
                <div class=Play_such>账号编号:</div>
                <div class="Play_such">绑定电话:</div>
                <div class="Play_such">邮箱:</div>
                <div class="Play_such">
                    <button type="button" class="btn btn-primary">修改密码
                    </button>
                    <button type="button" class="btn btn-primary"
                            onclick="window.location.href = '{% url 'users:logout' %}'">注销
                    </button>
                </div>
            </div>
        {% else %}
            <button type="button" class="btn btn-light"><a href="{% url "users:login" %}"
                                                           class="a_btn">登录</a>
            </button>
            </a>
            &nbsp;
            <button type="button" class="btn btn-light"><a href="{% url "users:register" %}"
                                                           class="a_btn">注册</a>
            </button>
        {% endif %}
        </form>
        </div>
    </div>
</nav>

<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div>
</body>
</html>

ledger/templates/ledger/details.html
{% extends "ledger/base.html" %}
{% block header %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
{% endblock header %}
{% block content %}
    <body>

    </body>
{% endblock content %}
</html>

ledger/templates/ledger/help.html
{% extends "ledger/base.html" %}
{% block header %}
    <!DOCTYPE html>
    <html lang="zh">
    <head>
        <meta charset="UTF-8">
        <title>FAQ</title>
    </head>
{% endblock header %}
{% block content %}
    <body>
    <div class="p-3 mb-2 text-white bg-dark">Q1：为什么“默认账本”不能删除？<br>
        A1：由于“默认账本”属于默认生成的，为了避免误删。系统只允许修改，而不能删除的哦！
    </div>
    <div class="p-3 mb-2 text-white bg-dark">Q2：我建立了几个新账本。能不能重新排序？<br>
        A2：不可以的，目前以建立先后时间排序的呢。
    </div>
    <div class="p-3 mb-2 text-white bg-dark">Q3：我常常会忘记记账。有什么办法更方便的登录你们的网站？<br>
        A3：首页这里有一个“创建桌面快捷方式”，您只要点击后根据提示操作就可以了。
    </div>
    <div class="p-3 mb-2 text-white bg-dark">Q4：朋友向我借了一笔钱，他还钱时我要怎么记收款？<br>
        A4：首先您已经在“借入/借出”这里记入了一笔借出款。记收款时在账目清单选中这笔账，旁边会出现“结清”按钮，这时您只要点击并填入金额就可以。
    </div>

    </body>
{% endblock content %}
</html>

ledger/templates/ledger/record.html
{% extends "ledger/base.html" %}
{% load static %}
{% block header %}
    <!DOCTYPE html>
    <html lang="zh">
    <head>
        <meta charset="UTF-8">
        <title>记一笔</title>
        <script>
            $.ajax({
                url: "/static/data/categories.csv",
                success: function (result) {
                    TypeList = result.split("\n");
                    for (var i = 1; i < TypeList.length; i++) {
                        ary = TypeList[i].split(",");
                        var opEle = document.createElement("option");
                        opEle.innerHTML = ary[2];
                        var sele = document.getElementById("category");
                        sele.appendChild(opEle);
                    }
                },
                error: function () {
                    console.log("error!");
                }
            })
        </script>


    </head>
{% endblock header %}
{% block content %}
    <body>
    <form action="{% url "ledger:form_submit" %}">
        <div class="mb-3">
            <label for="time" class="form-label text-primary">日期</label>
            <br><input type="text" class="form-control" name="date" id="time">
        </div>

        <div>
            <label for="sort" class="form-label text-primary">类别</label>
            <select class="form-select" aria-label="Default select example" id="sort" name="sort" required>
                <option selected="selected" disabled="disabled" style='display: none' value=''></option>
                <option>收入</option>
                <option>支出</option>
            </select>
        </div>

        <div>
            <label for="category" class="form-label text-primary">分类</label>
            <select class="form-select" aria-label="Default select example" id="category" name="type" required>
                <option selected="selected" disabled="disabled" style='display: none' value=''></option>
            </select>
        </div>

        <div class="mb-3">
            <label for="money" class="form-label text-primary">金额</label>
            <input type="number" class="form-control" id="money" aria-describedby="emailHelp" name="money"
                   required="required">
        </div>

        <button type="submit" class="btn btn-primary">保存</button>
    </form>

    <script type="text/javascript">
        function todayTime() {
            var today = new Date();
            var y = today.getFullYear();
            var m = today.getMonth() + 1;
            var d = today.getDate();
            var H = today.getHours();
            var M = today.getMinutes();
            var S = today.getSeconds();
            return y + "-" + (m < 10 ? "0" + m : m) + "-" + (d < 10 ? "0" + d : d) +
                " " + (H < 10 ? "0" + H : H) + ":" + (M < 10 ? "0" + M : M) + ":" + (S < 10 ? "0" + S : S);
        }

        document.getElementById("time").value = todayTime();
    </script>

    </body>
{% endblock content %}
</html>

users/templates/users/login.html
{% extends "ledger/base.html" %}

{% block title %}登录{% endblock %}
{% block header %}
    <style>
        body {
            background-color: #ffffff;
        }

        .form-login {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }

        .form-login .form-control {
            position: relative;
            height: auto;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            padding: 10px;
            font-size: 16px;
        }

        .form-login .form-control:focus {
            z-index: 2;
        }

        .form-login input[type="text"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-login input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
{% endblock header %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-login' action="{% url "users:login" %}" method="post">

                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}

                {% csrf_token %}
                <h2 class="text-center">欢迎登录</h2>
                <div class="form-group">
                    <label for="id_username">用户名：</label>
                    <input type="text" name='username' class="form-control" id="id_username"
                           autofocus required>
                </div>
                <div class="form-group">
                    <label for="id_password">密码：</label>
                    <input type="password" name='password' class="form-control" id="id_password"
                           required>
                </div>
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "ledger/base.html" %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>注册账号</title>
</head>
<body>
{% block content %}
    <form class="row g-3">
        <div class="col-md-4">
            <label for="validationDefault01" class="form-label">姓名</label>
            <input type="text" class="form-control" id="validationDefault01" required>
        </div>
        <div class="col-md-4">
            <label for="validationDefault02" class="form-label">性别</label>
            <input type="text" class="form-control" id="validationDefault02" required>
        </div>
        <div class="col-md-4">
            <label for="validationDefaultUsername" class="form-label">昵称</label>
            <div class="input-group">
                <span class="input-group-text" id="inputGroupPrepend2">@</span>
                <input type="text" class="form-control" id="validationDefaultUsername"
                       aria-describedby="inputGroupPrepend2" placeholder="取一个好听的名字吧" required>
            </div>
        </div>
        <div class="col-md-3">
            <label for="validationDefault04" class="form-label">身份</label>
            <select class="form-select" id="validationDefault04" required>
                <option selected disabled value="">下拉选择...</option>
                <option>学生</option>
                <option>事业单位</option>
                <option>商业/企业</option>
                <option>医护</option>
                <option>金融/银行</option>
                <option>互联网</option>
                <option>广告传媒</option>
            </select>
        </div>
        <div class="col-md-3">
            <label for="validationDefault05" class="form-label">邮箱</label>
            <input type="text" class="form-control" id="validationDefault05" placeholder="方便重置和找回密码" required>
        </div>
        <div class="col-md-3">
            <label for="validationDefault06" class="form-label">电话号码</label>
            <input type="text" class="form-control" id="validationDefault06" required>
        </div>
        <div class="col-12">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="invalidCheck2" required>
                <label class="form-check-label" for="invalidCheck2">
                    同意条款和条件
                </label>
            </div>
        </div>
        <div class="col-12">
            <button class="btn btn-primary" type="submit">确定提交</button>
        </div>
    </form>
{% endblock content %}
</body>
</html>